language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://ayush1.pact.dius.com.au/
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "UDl/i5LR7t8RsHk3wCsmdXpRmRg0FLFqzhj6ZAZc5snbV2NBlh5Ro1EQhSxO9CRYC2JuTEaL+10dDThDTEZoHpB3cL2/fwXUURSGCaPGc0oshxYCmGmygAvIHTH3granBIXLWcJwDDQp/NcwFkr+JB1f0eQtgcHXOQPggpayTVPLgDi0rfL+XEUoY1DkkL6cjQ/e/KR7uSdV77pVRLJ15CfDHIbMxjiSYcIwoWDlA18rRuTD6LHx5350bUXB9VxGVZwMpQdi0CZgNM16Uix2IIEDOoJJg0QS/mljX14ZNebA/b2aQpSvOkQVpRLXu/7VDomArG80OFRCSKM+iuf2mJTw1HZPnRfnNONFyihcngf81NZckeeCLDsyjo6Lg6QUx8W1Nc6Pkh4BLvR4xVhyyatIqfc+pQyE0crlyr6236rLi7SybG8KgeMqOsnGoozV1JkukzG1yJQbp7VpOMfyjDfyk+mOkin5EknDK8IX+xej/louq3P5byGj5XDwmHWil4QbH4xn9CCnXg5CW+7Kast8IcDQwwZxmDtaoHPyJ2sj2KwXXz1uaYEEEj9W6RfBSLOkpwTqWqb/ClwmROVXtywt9hnrc8dizlfv5V9hUxJ6IOfgJXvSaOYyo1k+so2KC+WYJjvl6skcfygUKenmVgjrBohH6+PgfWIfW+VOkGY="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
