language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://test.pact.dius.com.au
    - PACT_BROKER_USERNAME=dXfltyFMgNOFZAxr8io9wJ37iUpY42M
    - PACT_BROKER_PASSWORD=O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
script:
  # When a webhook triggers this, PACT_URL will be set
  # Otherwise, run the normal build.
  # This is just to get around the fact that
  # Travis CI only has one pipeline per repository
  - if [ -z "${PACT_URL}" ]; then make all; else make test; fi
